### ISSUE TITLE
Cannot generate any images

### ISSUE THREAD

**Issue by ate214** [Engineer-of-Stuff/stable-diffusion-paperspace#105]
I got this error whatever any situations i tried, seems that the temporary path got wrecked.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1326, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1260, in postprocess_data
>     prediction_value = block.postprocess(prediction_value)
>   File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 4461, in postprocess
>     file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
>   File "/storage/stable-diffusion/stable-diffusion-webui/modules/ui_tempdir.py", line 55, in save_pil_to_file
>     file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
>   File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
>     file = _io.open(dir, mode, buffering=buffering,
>   File "/usr/lib/python3.10/tempfile.py", line 695, in opener
>     fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
>   File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
>     fd = _os.open(file, flags, 0o600)
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/tmp3bg5zaff.png'

**Comment by Cyberes** [comment]
Seems like a Gradio issue. I'd see what's up with them. Also, make sure everything is up to date.
