### ISSUE TITLE
Import Error when running WebUI block

### ISSUE THREAD

**Issue by greeberss** [Engineer-of-Stuff/stable-diffusion-paperspace#120]
btw I can usually run this block without xformers, but now I've been getting this error

Traceback (most recent call last):
  File "/storage/stable-diffusion/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/initialize.py", line 39, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "/storage/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/storage/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/evaluation.py", line 6, in <module>
    import clip
  File "/usr/local/lib/python3.10/dist-packages/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/usr/local/lib/python3.10/dist-packages/clip/clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py)

**Comment by Cyberes** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863
