### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Boymerkz** [Engineer-of-Stuff/stable-diffusion-paperspace#17]
/notebooks/stable-diffusion-webui
Error loading script: wildcards.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 166, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "/notebooks/stable-diffusion-webui/scripts/wildcards.py", line 1
    See the ReadMe!
        ^
SyntaxError: invalid syntax

Checkpoint v1-5-pruned-emaonly.ckpt [81761151] not found; loading fallback stableckpt/animefull-latest/model.ckpt [e3b0c442]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [e3b0c442] from /notebooks/stable-diffusion-webui/models/Stable-diffusion/stableckpt/animefull-latest/model.ckpt
Error verifying pickled file from /notebooks/stable-diffusion-webui/models/Stable-diffusion/stableckpt/animefull-latest/model.ckpt:
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/safe.py", line 76, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/safe.py", line 97, in load
    check_pt(filename)
  File "/notebooks/stable-diffusion-webui/modules/safe.py", line 89, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/webui.py", line 157, in <module>
    webui()
  File "/notebooks/stable-diffusion-webui/webui.py", line 116, in webui
    initialize()
  File "/notebooks/stable-diffusion-webui/webui.py", line 77, in initialize
    modules.sd_models.load_model()
  File "/notebooks/stable-diffusion-webui/modules/sd_models.py", line 237, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/notebooks/stable-diffusion-webui/modules/sd_models.py", line 172, in load_model_weights
    if "global_step" in pl_sd:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Cyberes** [comment]
You messed up the models somehow. Delete `stable-diffusion-webui` and recreate it then redownload the models using the blocks in the notebook.
