### ISSUE TITLE
JSONDecodeError while launching the WebUI

### ISSUE THREAD

**Issue by monsterdoc** [Engineer-of-Stuff/stable-diffusion-paperspace#76]
Starting yesterday I receive JSONDecodeError error while running the WebUI block. Created completely new project on Paperspace and still facing the same issue. 
```
Traceback (most recent call last):
  File "/storage/stable-diffusion/stable-diffusion-webui/webui.py", line 286, in <module>
    webui()
  File "/storage/stable-diffusion/stable-diffusion-webui/webui.py", line 197, in webui
    initialize()
  File "/storage/stable-diffusion/stable-diffusion-webui/webui.py", line 98, in initialize
    modules.sd_models.setup_model()
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model
    list_models()
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/sd_models.py", line 126, in list_models
    checkpoint_info = CheckpointInfo(filename)
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/sd_models.py", line 48, in __init__
    self.sha256 = hashes.sha256_from_cache(self.filename, "checkpoint/" + name)
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/hashes.py", line 50, in sha256_from_cache
    hashes = cache("hashes")
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/hashes.py", line 30, in cache
    cache_data = json.load(file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Cyberes** [comment]
I'd open an issue on the WebUI repo.

**Comment by haiku-balls** [comment]
Delete cache.json and the lock one in stable-diffusion's directory. Works for me when I retry after deleting them.
